server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_rating
    username: root
    password: santosh@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariCP
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: RATING-SERVICE
  cloud:
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        service-name: ${spring.application.name}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 15s
        health-check-timeout: 5s
        instance-id: ${spring.application.name}:${server.port}
        register: true
        deregister: true
        tags:
          - rating-service
          - spring-boot
        metadata:
          version: 1.0.0
          environment: development